apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "strray-framework.fullname" . }}-config
  labels:
    {{- include "strray-framework.labels" . | nindent 4 }}
data:
  codex.json: |
{{ .Values.config.codex | toJson | indent 4 }}